Repository microsoft/lsprotocol, pull requests merged in 2022-10, with the labels that each got.

#91 Update packages.
  generator/requirements.txt
  requirements.txt
  tests/requirements.txt
Labels: debt

#92 Update version
  pyproject.toml
Labels: no-changelog

#98 Add missing hook for Semantic Token capabilities.
  generator/requirements.txt
  lsprotocol/_hooks.py
  lsprotocol/validators.py
  requirements.txt
  tests/requests/test_initilize_request.py
  tests/requests/test_workspace_sematic_tokens_refresh.py
  tests/requirements.txt
Labels: bug

#100 Fix some errors detected by `mypy`
  generator/utils.py
  lsprotocol/converters.py
  lsprotocol/validators.py
  pyproject.toml
Labels: debt

#105 Remove code to autogenerate hooks.
  generator/utils.py
  lsprotocol/_hooks.py
  lsprotocol/converters.py
Labels: bug

#106 Support custom values for enums.
  generator/lsp.json
  generator/utils.py
  lsprotocol/_hooks.py
  lsprotocol/types.py
  noxfile.py
Labels: bug

#107 Add missing markup content hook.
  lsprotocol/_hooks.py
  tests/test_cattrs_special_cases.py
Labels: bug

#109 fix markup content hook
  lsprotocol/_hooks.py
Labels: bug
