Repository microsoft/lsprotocol, pull requests merged in 2022-08, with the labels that each got.

#42 Update packages.
  generator/requirements.txt
  requirements.txt
  tests/requirements.txt
Labels: no-changelog

#46 Update jsonschema
  .github/dependabot.yml
  .github/release.yml
  generator/requirements.txt
  tests/requirements.txt
Labels: no-changelog

#47 Generate types with snake case properties.
  .github/workflows/pr-check.yml
  .gitignore
  generator/utils.py
  lsprotocol/converters.py
  lsprotocol/types.py
  noxfile.py
  tests/requirements.txt
  tests/test_cattrs_special_cases.py
Labels: feature-request

#55 Add code review chat
  .github/workflows/pr-chat.yml
Labels: no-changelog

#59 Fix missing types in code generation.
  generator/__main__.py
  generator/lsp.json
  generator/lsp.schema.json
  generator/model.py
  generator/requirements.txt
  generator/utils.py
  lsprotocol/types.py
  pyproject.toml
  tests/requirements.txt
  tests/test_import.py
Labels: bug

#64 Update dependencies.
  generator/requirements.txt
  tests/requirements.txt
Labels: no-changelog

#66 Update to latest LSP spec.
  generator/lsp.json
  generator/utils.py
  lsprotocol/converters.py
  lsprotocol/types.py
  noxfile.py
  tests/test_cattrs_special_cases.py
Labels: bug

#70 Add comparison methods to few types.
  generator/requirements.txt
  generator/utils.py
  lsprotocol/types.py
  noxfile.py
  tests/requirements.txt
  tests/test_location.py
  tests/test_position.py
  tests/test_range.py
Labels: feature-request

#75 Ensure all mixin properties are included in the generated code.
  generator/utils.py
  lsprotocol/types.py
Labels: bug

#76 Update packages.
  generator/requirements.txt
  pyproject.toml
  tests/requirements.txt
Labels: debt
