Repository microsoft/lsprotocol, pull requests merged in 2023-07, with the labels that each got.

#231 Use new release pipeline
  azure-pipelines/release-pypi.yml
Labels: debt

#235 Skip notice file generation
  azure-pipelines/release-pypi.yml
Labels: debt

#234 Add devcontainer support to repo
  .devcontainer/devcontainer.json
Labels: feature-request

#236 Add generator packaging info
  .vscode/launch.json
  generator/__main__.py
  generator/plugins/__init__.py
  generator/plugins/dotnet/__init__.py
  generator/plugins/dotnet/custom/CustomObjectConverter.cs
  generator/plugins/dotnet/custom/CustomStringConverter.cs
  generator/plugins/dotnet/custom/Direction.cs
  generator/plugins/dotnet/custom/DocumentSelectorConverter.cs
  generator/plugins/dotnet/custom/IMessage.cs
  generator/plugins/dotnet/custom/INotification.cs
  generator/plugins/dotnet/custom/IOrType.cs
  generator/plugins/dotnet/custom/IPartialResultParams.cs
  generator/plugins/dotnet/custom/IRequest.cs
  generator/plugins/dotnet/custom/IResponse.cs
  generator/plugins/dotnet/custom/IResponseError.cs
  generator/plugins/dotnet/custom/LSPAnyConverter.cs
  generator/plugins/dotnet/custom/MessageDirection.cs
  generator/plugins/dotnet/custom/OrType.cs
  generator/plugins/dotnet/custom/OrTypeArrayConverter.cs
  generator/plugins/dotnet/custom/OrTypeConverter.cs
  generator/plugins/dotnet/custom/Proposed.cs
  generator/plugins/dotnet/custom/Since.cs
  generator/plugins/dotnet/custom/Validators.cs
  generator/plugins/dotnet/dotnet_classes.py
  generator/plugins/dotnet/dotnet_commons.py
  generator/plugins/dotnet/dotnet_constants.py
  generator/plugins/dotnet/dotnet_enums.py
  generator/plugins/dotnet/dotnet_helpers.py
  generator/plugins/dotnet/dotnet_special_classes.py
  generator/plugins/dotnet/dotnet_utils.py
  generator/plugins/python/__init__.py
  generator/plugins/python/utils.py
  generator/plugins/rust/__init__.py
  generator/plugins/rust/rust_commons.py
  generator/plugins/rust/rust_constants.py
  generator/plugins/rust/rust_enum.py
  generator/plugins/rust/rust_file_header.py
  generator/plugins/rust/rust_lang_utils.py
  generator/plugins/rust/rust_structs.py
  generator/plugins/rust/rust_utils.py
  generator/plugins/testdata/__init__.py
  generator/plugins/testdata/testdata_generator.py
  generator/plugins/testdata/testdata_utils.py
  noxfile.py
  pyproject.toml
  setup.cfg
Labels: debt

#238 Remove unused `--schema` switch
  generator/__main__.py
Labels: debt

#239 Add `--output-dir` switch to code generator
  generator/__main__.py
  generator/plugins/dotnet/dotnet_utils.py
  generator/plugins/python/utils.py
  generator/plugins/rust/rust_utils.py
  noxfile.py
Labels: feature-request

#242 Update usage details
  README.md
Labels: no-changelog

#243 Add response types and improve test suite
  .github/dependabot.yml
  .github/workflows/pr-check.yml
  generator/plugins/dotnet/custom/IResponse.cs
  generator/plugins/dotnet/custom/IResponseError.cs
  generator/plugins/dotnet/custom/LSPRequest.cs
  generator/plugins/dotnet/custom/LSPResponse.cs
  generator/plugins/dotnet/custom/OrTypeArrayConverter.cs
  generator/plugins/dotnet/custom/OrTypeConverter.cs
  generator/plugins/dotnet/custom/ResponseError.cs
  generator/plugins/dotnet/dotnet_classes.py
  generator/plugins/testdata/testdata_generator.py
  tests/dotnet/lsprotocol_tests/LSPTests.cs
Labels: feature-request

#250 Improve documentation tags in generated code
  generator/plugins/dotnet/dotnet_helpers.py
Labels: bug

#251 Fix warning with generated converter code
  generator/plugins/dotnet/dotnet_classes.py
Labels: bug

#252 Generate dotnet project package.
  .github/actions/build-package/action.yml
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
Labels: feature-request

#257 Format Generated Code
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
Labels: feature-request

#258 Use `record` instead of `class` for LSP types.
  generator/plugins/dotnet/custom/OrType.cs
  generator/plugins/dotnet/dotnet_classes.py
  generator/plugins/dotnet/dotnet_helpers.py
  generator/plugins/dotnet/dotnet_special_classes.py
Labels: feature-request

#256 Use ImmutableArray and ImmutableDictionary
  generator/plugins/dotnet/custom/CustomArrayConverter.cs
  generator/plugins/dotnet/custom/CustomObjectConverter.cs
  generator/plugins/dotnet/custom/DocumentSelectorConverter.cs
  generator/plugins/dotnet/custom/OrType.cs
  generator/plugins/dotnet/custom/OrTypeArrayConverter.cs
  generator/plugins/dotnet/custom/OrTypeConverter.cs
  generator/plugins/dotnet/dotnet_classes.py
  generator/plugins/dotnet/dotnet_helpers.py
  tests/dotnet/lsprotocol_tests/LSPTests.cs
Labels: feature-request
