Repository microsoft/lsprotocol, pull requests merged in 2023-03, with the labels that each got.

#173 Fix build paths and formatting
  .github/actions/build-package/action.yml
  .github/actions/lint/action.yml
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pr-check.yml
  .github/workflows/pr-labels.yml
  .github/workflows/push-check.yml
  .github/workflows/version-check.yml
  azure-pipelines/template/build_packages.yml
  azure-pipelines/template/publish_pypi.yml
  azure-pipelines/template/static_analysis.yml
Labels: debt

#174 Preserve types for backwards compatibility.
  generator-plugins/python/utils.py
  packages/python/lsprotocol/types.py
Labels: bug

#175 Update version for pre-release.
  packages/python/pyproject.toml
Labels: no-changelog

#176 Remove unused plugin from debug config
  .vscode/launch.json
Labels: no-changelog

#177 Add `pygls` repository tests as smoke test
  .github/workflows/pr-check.yml
  .prettierrc.js
  .vscode/extensions.json
Labels: debt

#179 Introduce lower bound on `attrs` version
  packages/python/pyproject.toml
Labels: bug

#182 Update readme
  README.md
Labels: no-changelog

#186 Update and consolidate dependencies
  README.md
  generator/requirements.in
  noxfile.py
  packages/python/requirements.txt
  requirements.in
  requirements.txt
  tests/generator/requirements.txt
  tests/python/requirements.in
  tests/python/requirements.txt
Labels: debt

#185 Auto create issue when LSP spec changes upstream
  .github/workflows/lsp_updater.py
  .github/workflows/updater.yml
  .github/workflows/version_check.py
  .vscode/settings.json
  generator/lsp.schema.json
  noxfile.py
Labels: no-changelog

#188 Fix python version
  .github/workflows/updater.yml
Labels: no-changelog
