Repository microsoft/lsprotocol, pull requests merged in 2023-09, with the labels that each got.

#267 Dev Container for lsprotocol
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  scripts/onCreateCommand.sh
  scripts/postCreateCommand.sh
Labels: feature-request

#268 Add pyproject.toml path to lsprotocol project build
  azure-pipelines/release-pypi.yml
Labels: debt

#272 Add PositionEncodingKind hook
  packages/python/lsprotocol/_hooks.py
  tests/python/test_cattrs_special_cases.py
Labels: bug

#273 Add broad spectrum tests for python
  noxfile.py
  packages/python/lsprotocol/_hooks.py
  tests/python/test_generated_data.py
Labels: bug

#275 Update to latest LSP spec
  generator/lsp.json
  packages/python/lsprotocol/types.py
  packages/python/pyproject.toml
  packages/rust/lsprotocol/src/lib.rs
Labels: feature-request
