Repository microsoft/lsprotocol, pull requests merged in 2023-08, with the labels that each got.

#260 Fix for missing notebook selector hook
  packages/python/lsprotocol/_hooks.py
  tests/python/test_cattrs_special_cases.py
Labels: bug

#262 Update packages to latest LSP model
  generator/lsp.json
  noxfile.py
  packages/python/lsprotocol/types.py
  packages/python/requirements.txt
  packages/rust/lsprotocol/src/lib.rs
  requirements.txt
Labels: debt

#264 Update to latest lsp spec
  generator/lsp.json
  packages/python/lsprotocol/types.py
  packages/rust/lsprotocol/src/lib.rs
Labels: debt, lsp-update

#265 Use default package location
  azure-pipelines/release-pypi.yml
Labels: no-changelog
