Repository microsoft/lsprotocol, pull requests merged in 2023-11, with the labels that each got.

#281 Update to latest LSP spec
  generator/lsp.json
  packages/python/lsprotocol/_hooks.py
  packages/python/pyproject.toml
Labels: debt

#284 Update package classifiers
  packages/python/pyproject.toml
Labels: bug

#285 Use Sequence instead of List
  generator/plugins/python/utils.py
  packages/python/lsprotocol/_hooks.py
  packages/python/lsprotocol/types.py
Labels: bug

#286 Update to latest LSP spec with type name changes
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  .github/workflows/version_check.py
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  azure-pipelines/release-pypi.yml
  azure-pipelines/release.yml
  azure-pipelines/template/build_packages.yml
  azure-pipelines/template/publish_pypi.yml
  conftest.py
  generator/__main__.py
  generator/lsp.json
  generator/model.py
  generator/plugins/dotnet/__init__.py
  generator/plugins/dotnet/dotnet_classes.py
  generator/plugins/dotnet/dotnet_enums.py
  generator/plugins/dotnet/dotnet_helpers.py
  generator/plugins/dotnet/dotnet_special_classes.py
  generator/plugins/dotnet/dotnet_utils.py
  generator/plugins/python/__init__.py
  generator/plugins/python/utils.py
  generator/plugins/rust/__init__.py
  generator/plugins/rust/rust_commons.py
  generator/plugins/rust/rust_constants.py
  generator/plugins/rust/rust_enum.py
  generator/plugins/rust/rust_structs.py
  generator/plugins/rust/rust_tests.py
  generator/plugins/rust/rust_utils.py
  generator/plugins/testdata/__init__.py
  generator/plugins/testdata/testdata_generator.py
  generator/plugins/testdata/testdata_utils.py
  lsprotocol.sln
  noxfile.py
  packages/python/lsprotocol/_hooks.py
  packages/python/lsprotocol/types.py
  packages/python/pyproject.toml
  packages/python/requirements.txt
  packages/rust/lsprotocol/Cargo.toml
  packages/rust/lsprotocol/src/lib.rs
  requirements.txt
  runtime.txt
  scripts/onCreateCommand.sh
  tests/generator/test_model.py
  tests/python/common/jsonrpc.py
  tests/python/notifications/test_progress.py
  tests/python/requests/test_inlay_hint_resolve_request.py
  tests/python/test_cattrs_special_cases.py
  tests/python/test_custom_validators.py
  tests/python/test_enums.py
  tests/python/test_generated_data.py
  tests/python/test_location.py
  tests/python/test_position.py
  tests/python/test_range.py
  tests/rust/Cargo.toml
  tests/rust/src/main.rs
Labels: feature-request

#288 `mypy` update changed linting rules
  packages/python/lsprotocol/_hooks.py
Labels: bug

#290 Adds type alias for result types
  .vscode/settings.json
  generator/plugins/python/utils.py
  packages/python/lsprotocol/types.py
Labels: feature-request

#291 Update toml for rust packages
  packages/rust/lsprotocol/Cargo.toml
  tests/rust/Cargo.toml
  tests/rust/src/main.rs
Labels: debt

#292 Update package version and readme
  .vscode/settings.json
  packages/rust/lsprotocol/Cargo.toml
  packages/rust/lsprotocol/README.md
Labels: debt

#293 Add alpha version to rust package
  packages/rust/lsprotocol/Cargo.toml
Labels: debt

#295 Dotnet change `uint` to `long`
  generator/plugins/dotnet/custom/OrTypeConverter.cs
  generator/plugins/dotnet/custom/Validators.cs
  generator/plugins/dotnet/dotnet_classes.py
Labels: feature-request

#296 Remove types preserved from backwards compat
  generator/plugins/python/utils.py
  packages/python/lsprotocol/types.py
Labels: bug

#299 Fix classifiers for pre-release version
  packages/python/pyproject.toml
Labels: bug

#303 Tighten cattrs dependency
  packages/python/pyproject.toml
  requirements.in
Labels: bug

#305 Tighten cattrs dependency
  packages/python/pyproject.toml
  requirements.in
Labels: bug

#307 Update version to 2023.0.1
  .vscode/settings.json
  packages/python/pyproject.toml
Labels: no-changelog
