Repository microsoft/lsprotocol, pull requests merged in 2024-08, with the labels that each got.

#371 Update version for pypi
  packages/python/pyproject.toml
Labels: no-changelog

#373 Update to latest pytest and attrs
  packages/python/requirements.txt
  requirements.txt
  tests/python/test_cattrs_special_cases.py
Labels: debt

#378 Fix root directory in release template
  azure-pipelines/release-pypi.yml
Labels: no-changelog

#379 Fix root directory in main template
  azure-pipelines/release-pypi.yml
Labels: no-changelog

#380 chore: fix publish task
  azure-pipelines/release-pypi.yml
Labels: no-changelog

#381 chore: fix publish task
  azure-pipelines/release-pypi.yml
Labels: debt

#383 Remove unnecessary publish step
  azure-pipelines/release-pypi.yml
Labels: no-changelog

#382 Remove unnecessary publish step
  azure-pipelines/release-pypi.yml
Labels: no-changelog

#388 Add support for TextDocumentContentResult
  generator/lsp.json
  packages/python/lsprotocol/types.py
  packages/rust/lsprotocol/src/lib.rs
  requirements.txt
Labels: feature-request

#389 Update package version for Python and Rust
  packages/python/pyproject.toml
  packages/rust/lsprotocol/Cargo.toml
Labels: no-changelog
