Repository microsoft/lsprotocol, pull requests merged in 2024-10, with the labels that each got.

#401 Code Action Tag for LLMs
  generator/__main__.py
  generator/lsp.json
  packages/python/lsprotocol/types.py
  packages/python/pyproject.toml
  packages/python/requirements.txt
  packages/rust/lsprotocol/src/lib.rs
  requirements.txt
Labels: debt

#402 Fix development class
  packages/python/pyproject.toml
Labels: bug

#403 Add Crystal plugin to README
  README.md
Labels: documentation, feature-request

#404 Add coverage support
  .github/workflows/pr-check.yml
  noxfile.py
  tests/python/test_misc.py
Labels: debt

#406 Breaking change to `ApplyKind` from LSP Spec
  generator/lsp.json
  packages/python/lsprotocol/types.py
  packages/rust/lsprotocol/src/lib.rs
Labels: bug
