Repository microsoft/lsprotocol, pull requests merged in 2025-05, with the labels that each got.

#415 Python generator: use Mapping instead of Dict for type annotations
  generator/plugins/python/utils.py
  packages/python/lsprotocol/types.py
Labels: bug

#418 Add golang to plugin table
  README.md
Labels: no-changelog

#421 Rewrite release pipeline to use MicroBuild rather than vscode's templates
  RELEASE.md
  azure-pipelines/release-pypi.yml
Labels: debt

#422 Change `pyproject.toml` version to `2025.0.0rc1`
  RELEASE.md
  packages/python/pyproject.toml
Labels: no-changelog
